# Generated by Django 4.2.4 on 2023-08-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_alter_myuser_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='organizer',
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
