# Generated by Django 4.2.4 on 2023-09-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0003_remove_meetup_organizer_meetup_organizer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='img',
            new_name='image',
        ),
    ]
