# Generated by Django 4.2.4 on 2023-09-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0004_rename_img_myuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='proffession',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
