# Generated by Django 4.2.4 on 2023-09-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0005_speaker_proffession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=200, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='testimonial_img')),
            ],
        ),
        migrations.AlterField(
            model_name='meetup',
            name='meetup_speakers',
            field=models.ManyToManyField(blank=True, to='meetup.speaker'),
        ),
    ]
