# Generated by Django 4.2.4 on 2023-09-28 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0007_myuser_profession_speaker_intstagram_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='intstagram',
            new_name='instagram',
        ),
    ]
